//CONSTANTS
export const CHANGE_QUERY = 'CHANGE_QUERY';
export const REQUEST_STATUSES = 'REQUEST_STATUSES';
export const RECEIVE_STATUSES_SUCCESS = 'RECEIVE_STATUSES_SUCCESS';
export const RECEIVE_STATUSES_ERROR = 'RECEIVE_STATUSES_ERROR';
export const OPEN_MODAL = 'OPEN_MODAL';
